{"contatos": [ { "addresses" : null,
    "birthday" : null,
    "categories" : null,
    "displayName" : "Rodnei Couto",
    "emails" : null,
    "id" : "1",
    "ims" : null,
    "name" : { "familyName" : "Couto",
        "formatted" : "Rodnei Couto",
        "givenName" : "Rodnei"
      },
    "nickname" : null,
    "note" : null,
    "organizations" : null,
    "phoneNumbers" : [ { "id" : "1",
          "pref" : false,
          "type" : "mobile",
          "value" : "(21)99999-8888"
        } ],
    "photos" : null,
    "rawId" : "1",
    "urls" : null
  },
  { "addresses" : null,
    "birthday" : null,
    "categories" : null,
    "displayName" : "Pedro Silva",
    "emails" : null,
    "id" : "2",
    "ims" : null,
    "name" : { "familyName" : "Silva",
        "formatted" : "Pedro Silva",
        "givenName" : "Pedro"
      },
    "nickname" : null,
    "note" : null,
    "organizations" : null,
    "phoneNumbers" : [ { "id" : "4",
          "pref" : false,
          "type" : "home",
          "value" : "(21)98888-9999"
        } ],
    "photos" : null,
    "rawId" : "2",
    "urls" : null
  }
]}